<?php 
    $title = "System Logging";
    $path = "../";

    include($path."assets/inc/header.php");

    include($path."assets/inc/nav.php");

?>

<main class="content_body">
     
<div>
    <h1>System Logging on Unix: A Tutorial</h1>
    <p>Welcome to the tutorial on system logging on Unix-like systems!</p>

    <h2>1. System Logging</h2>
    <p>System logging involves capturing various types of messages and events generated by the operating system, kernel, and applications and storing them in log files for later analysis.</p>

    <h2>2. Syslog Facilities</h2>
    <p>Syslog uses facilities to categorize log messages based on their source or type. Examples of facilities include kern (kernel messages), auth (authentication messages), and mail (mail server messages).</p>

    <h2>3. Syslog Priorities</h2>
    <p>Syslog priorities (or severity levels) indicate the importance of a log message. They range from emergency (most critical) to debug (least critical), with other levels like alert, critical, error, warning, notice, and info in between.</p>

    <h2>4. The /etc/syslog.conf File</h2>
    <p>The <code>/etc/syslog.conf</code> file (or <code>/etc/rsyslog.conf</code> in some distributions) is the configuration file for the syslog daemon. It specifies where log messages should be stored, how they should be formatted, and what actions should be taken based on their facility and priority.</p>

    <h2>5. Logging Actions</h2>
    <p>Logging actions in the syslog configuration file define what should happen to log messages based on their facility and priority. Actions can include storing messages in files, forwarding them to remote syslog servers, executing commands, or sending them to specific users.</p>

    <h2>6. The logger Command</h2>
    <p>The <code>logger</code> command is a command-line utility used to manually create log messages. It allows users or scripts to generate custom log messages that can be logged by the syslog daemon.</p>

    <h2>7. Log Rotation</h2>
    <p>Log rotation is the process of managing log files to prevent them from becoming too large and consuming too much disk space. Log rotation typically involves compressing old log files, renaming them, and starting new log files to continue logging.</p>

    <h2>8. Important Log Locations</h2>
    <p>System logs are typically stored in various locations on Unix-like systems, such as <code>/var/log/messages</code>, <code>/var/log/syslog</code>, <code>/var/log/auth.log</code>, and others, depending on the distribution and configuration.</p>

    <h2>Conclusion</h2>
    <p>Understanding system logging is crucial for monitoring system health, troubleshooting issues, and maintaining system security on Unix-like systems.</p>
</div>


</main>

<?php 
    include($path."assets/inc/footer.php");
?>